name: mpt
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - torch==2.0.0
      - torchvision==0.15.1
      - numpy==1.26.4
      - opencv-python==4.8.0.74
      - path.py==12.5.0
      - tqdm==4.65.0
      - matplotlib==3.7.1
      - einops==0.8.1
      - timm==0.9.5
      - yacs==0.1.8
      - scipy==1.10.1
      - ptflops==0.7.5
      - lpips==0.1.4
      - scikit-image==0.21.0
